DEBUG 2016-01-15 13:46:28,404: 	 Executing command: 'submit'
DEBUG 2016-01-15 13:46:28,405: 	 Found CRAB cache file /home/janjamrk/.crab3
DEBUG 2016-01-15 13:46:28,419: 	 Checking credentials
DEBUG 2016-01-15 13:46:28,420: 	 Found proxy file /tmp/x509up_u171357
DEBUG 2016-01-15 13:46:28,420: 	 Getting proxy life time left
DEBUG 2016-01-15 13:46:28,523: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-01-15 13:46:28,523: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-01-15 13:46:28,523: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-01-15 13:46:32,333: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 3
DEBUG 2016-01-15 13:46:32,437: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-01-15 13:46:32,540: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u171357 voms-proxy-info -fqan
 output : 
 error: 
 retcode : 1
ERROR 2016-01-15 13:46:32,540: 	 Problems creating proxy.
ERROR 2016-01-15 13:46:32,540: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 32, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 289, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-01-18 08:55:22,881: 	 Executing command: 'status'
DEBUG 2016-01-18 08:55:22,885: 	 Found CRAB cache file /home/janjamrk/.crab3
DEBUG 2016-01-18 08:55:22,896: 	 Checking credentials
DEBUG 2016-01-18 08:55:22,897: 	 Proxy file /tmp/x509up_u171357 not found
DEBUG 2016-01-18 08:55:22,897: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-01-18 08:55:27,407: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2016-01-18 08:55:27,510: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-01-18 08:55:27,613: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -actimeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-01-18 08:55:27,716: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u171357 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2016-01-18 08:55:27,716: 	 Proxy created.
ERROR 2016-01-18 08:55:27,716: 	 Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
ERROR 2016-01-18 08:55:27,716: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 428, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
DEBUG 2016-01-18 11:05:22,127: 	 Executing command: 'status'
DEBUG 2016-01-18 11:05:22,128: 	 Found CRAB cache file /home/janjamrk/.crab3
DEBUG 2016-01-18 11:05:22,135: 	 Checking credentials
DEBUG 2016-01-18 11:05:22,135: 	 Found proxy file /tmp/x509up_u171357
DEBUG 2016-01-18 11:05:22,136: 	 Getting proxy life time left
DEBUG 2016-01-18 11:05:22,238: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 78605

 error: 
 retcode : 0
DEBUG 2016-01-18 11:05:22,341: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -actimeleft
 output : 78605

 error: 
 retcode : 0
DEBUG 2016-01-18 11:05:22,342: 	 Proxy valid for 21:50:05 hours
ERROR 2016-01-18 11:05:22,342: 	 Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
ERROR 2016-01-18 11:05:22,342: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 428, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
DEBUG 2016-01-18 11:13:26,849: 	 Executing command: 'status'
DEBUG 2016-01-18 11:13:26,851: 	 Found CRAB cache file /home/janjamrk/.crab3
DEBUG 2016-01-18 11:13:26,865: 	 Checking credentials
DEBUG 2016-01-18 11:13:26,870: 	 Found proxy file /tmp/x509up_u171357
DEBUG 2016-01-18 11:13:26,870: 	 Getting proxy life time left
DEBUG 2016-01-18 11:13:27,074: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-01-18 11:13:27,074: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-01-18 11:13:27,075: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-01-18 11:13:33,590: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2016-01-18 11:13:33,694: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -timeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-01-18 11:13:33,799: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u171357 -actimeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-01-18 11:13:33,903: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u171357 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2016-01-18 11:13:33,903: 	 Proxy created.
ERROR 2016-01-18 11:13:33,904: 	 Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
ERROR 2016-01-18 11:13:33,904: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 428, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /gpfs22/home/janjamrk/CMSSW_7_5_8/src/TestAnalyzer_v1/TestAnalyzer_v1/python/pPbConfigs/pPb_crab_projects
